=== dk0104/Demo/XmlConnection/XmlConnectionTest/TestData/ProductPortofolioSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema name="ProductPortofolioSchema"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified"   
>
  <!--simple types-->
  <xs:simpleType name="stringtype">
    <xs:restriction base="xs:string"/>
  </xs:simpleType>

  <xs:simpleType name="dectype">
    <xs:restriction base="xs:decimal"/>
  </xs:simpleType>

  <xs:simpleType name="booltype">
    <xs:restriction base="xs:boolean"/>
  </xs:simpleType>

  <xs:simpleType name="datetype">
    <xs:restriction base="xs:date"/>
  </xs:simpleType>
  
  <!--product id type-->
  <xs:simpleType name="productnametype">
    <xs:restriction base="xs:positiveInteger">
      <xs:pattern value="[0-9]{6}"/>
    </xs:restriction>
  </xs:simpleType>
  
  <!--serial number type-->
  <xs:simpleType name="sernumber">
    <xs:restriction base="xs:string">
      <xs:pattern value="([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})|(\{[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\})"/>
    </xs:restriction>
  </xs:simpleType>

  <!--Complex Types-->
  <xs:complexType name="featureType">
    <xs:sequence>
      <xs:element name="featureName" type="stringtype"></xs:element>
      <xs:element name="featureDescription" type="stringtype"></xs:element>
      <xs:element name="isSelected" type ="booltype"></xs:element>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="productType">
    <xs:sequence>
      <xs:element name="productName" type="stringtype"></xs:element>
      <xs:element name="version" type="stringtype"></xs:element>
      <xs:element name="productDescription" type="stringtype"></xs:element>
      <xs:element name="features" maxOccurs="unbounded" type="featureType"></xs:element>
    </xs:sequence>
    <xs:attribute name="name" type="productnametype" use="required"></xs:attribute>
  </xs:complexType>

  <xs:complexType name ="orderType">
    <xs:sequence>
      <xs:element name="orderDate" type ="datetype"></xs:element>
      <xs:element name="orderProducts" maxOccurs="unbounded" type="productType"></xs:element>
      <xs:element name="serialnumber" type="sernumber"></xs:element>
    </xs:sequence>
  </xs:complexType>
  
  <!--Elements-->
  <xs:element name="products">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="product" type="productType" minOccurs="1" maxOccurs="unbounded"></xs:element>
      </xs:sequence>
    </xs:complexType>   
  </xs:element> 

  <xs:element name ="order" type="orderType"></xs:element>  
  
</xs:schema>

=== dk0104/Demo/XmlConnection/XmlConnectionTest/TestData/ProductPortofolio.xml
<?xml version="1.0" encoding="utf-8" ?>
<products xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="ProductPortofolioSchema.xsd">
  <product id="000001">
    <productName>ProductA</productName>
    <version>1.0</version>
    <productDescription>Product A Bla bla blup</productDescription>
    <features>
      <featureName>feature A</featureName>
      <featureDescription>Feature B is bla bla blup</featureDescription>
      <isSelected>false</isSelected>
    </features>
    <features>
      <featureName>feature B</featureName>
      <featureDescription>Feature B is bla bla blup</featureDescription>
      <isSelected>false</isSelected>
    </features>
  </product>
  <product id="000002">
    <productName>Product B</productName>
    <version>1.0</version>
    <productDescription>Product B Bla bla blup</productDescription>
    <features>
      <featureName>feature A</featureName>
      <featureDescription>Feature B is bla bla blup</featureDescription>
      <isSelected>false</isSelected>
    </features>
    <features>
      <featureName>feature B</featureName>
      <featureDescription>Feature B is bla bla blup</featureDescription>
      <isSelected>false</isSelected>
    </features>
  </product>
</products>
